import { PlanItem, Teacher, ClassUnit, Classroom, Course } from "../types";
import { SchoolScheduleConfig, getActivePeriodsCountForDay } from "./timeSettings";
import {
  UnassignedRequirement,
  ClassOptimizerReport,
  AtaOptimizerResult,
  normalizeSchedulingInput,
  getFinalConfig,
  validateSchedules,
  isAutoGeneratedPlan,
  isSchedulablePlan,
  isActiveEntity,
  canTeacherTeachCourse,
  isTeacherCadreCompatible,
  getCoursePedagogicalProfile,
  buildStartSlotCache,
  shuffleInPlace,
  buildBlockSlots,
  tryStageBlockOnIndex,
  scoreBlockPlacement,
  rollbackIndexedPlacements,
  keepBestCandidates,
  materializeCandidate,
  diagnoseUnassignedRequirement,
  getLevelPolicy,
  countAllowedSlotsForClass,
  buildScheduleIndex,
  createMulberry32,
  CandidateDraft
} from "./scheduler";
import { CLASS_TIME_WINDOWS } from "../data/initialData";

// Message interface for Worker
interface WorkerInputMessage {
  currentPlans: PlanItem[];
  teachers: Teacher[];
  classes: ClassUnit[];
  classrooms: Classroom[];
  courses: Course[];
  config?: SchoolScheduleConfig;
  options?: {
    optimizationMode?: "completeness" | "pedagogical" | "balanced";
    seed?: number;
  };
}

interface PendingAssignment {
  sinif: ClassUnit;
  courseObj: Course;
  eligibleTeachers: Teacher[];
  eligibleRooms: Classroom[];
  hours: number;
}

export function runAlgorithmicOptimizerSync(
  currentPlans: PlanItem[],
  teachers: Teacher[],
  classes: ClassUnit[],
  classrooms: Classroom[],
  courses: Course[],
  config?: SchoolScheduleConfig,
  options?: {
    optimizationMode?: "completeness" | "pedagogical" | "balanced";
    seed?: number;
  }
): AtaOptimizerResult {
  const logs: string[] = [];
  const unassignedRequirements: UnassignedRequirement[] = [];
  let resolvedCount = 0;
  const finalConfig = getFinalConfig(config);
  const normalizedInput = normalizeSchedulingInput(currentPlans, teachers, classes, classrooms, courses, finalConfig);
  let plansCopy = JSON.parse(JSON.stringify(currentPlans)) as PlanItem[];

  const optimizationMode = options?.optimizationMode || "balanced";
  const seed = options?.seed !== undefined ? options.seed : 42;
  const rng = createMulberry32(seed);

  logs.push("⚙️ Ata Akademi Web Worker Optimizasyon Motoru Başlatıldı.");
  logs.push(`Mevcut planlama sayısı: ${plansCopy.length} kart.`);
  logs.push(`🌱 Çözüm yöntemi tohumu (Seed - Web Worker): ${seed}`);
  if (optimizationMode === "completeness") {
    logs.push("🎯 Mod: Tamamlama modu (Ders bütünlüğü göz ardı edilir; tüm dersler 1 saatlik bağımsız bloklar halinde yerleştirilir).");
  } else if (optimizationMode === "pedagogical") {
    logs.push("🎓 Mod: Pedagojik mod (Çiftli ve üçlü bloklar sıkı şekilde korunur ve asla bölünmez).");
  } else {
    logs.push("⚖️ Mod: Dengeli mod (Önce pedagojik çiftli/üçlü bloklar denenir, yerleşemeyen kalan dersler 1 saatlik bağımsız bloklara bölünür).");
  }

  const initViolations = validateSchedules(plansCopy, teachers, classes, classrooms, courses, finalConfig);
  const hardViolations = initViolations.filter((violation) => violation.seviye === "Zorunlu");

  if (hardViolations.length > 0) {
    logs.push(`⚠️ Programda ${hardViolations.length} adet zorunlu kural ihlali bulundu. Sorunlu kartlar temizleniyor...`);

    const badIds = new Set<string>();
    hardViolations.forEach((violation) => violation.bilesenIds.forEach((id) => badIds.add(id)));

    const removableBadIds = new Set(
      [...badIds].filter((id) => {
        const plan = plansCopy.find((item) => item.id === id);
        return plan ? isAutoGeneratedPlan(plan) : false;
      })
    );

    const beforeCount = plansCopy.length;
    plansCopy = plansCopy.filter((plan) => !removableBadIds.has(plan.id));
    resolvedCount += beforeCount - plansCopy.length;

    logs.push(`${beforeCount - plansCopy.length} otomatik sorunlu kart kaldırıldı.`);
    if (badIds.size > removableBadIds.size) {
      logs.push(`${badIds.size - removableBadIds.size} manuel/mevcut kart silinmedi; kullanıcı kontrolü için programda korundu.`);
    }
  }

  let absoluteMinMissing = 0;
  classes.forEach((sinif) => {
    if (!sinif.aktifPasif) return;
    let requiredHours = 0;
    Object.entries(sinif.haftalikDersIhtiyaci || {}).forEach(([dersIsmi, iHour]) => {
      requiredHours += Number(iHour);
    });
    const allowedSlotsCount = countAllowedSlotsForClass(sinif, finalConfig, normalizedInput.effectiveAllowedPeriods);

    if (requiredHours > allowedSlotsCount) {
      absoluteMinMissing += (requiredHours - allowedSlotsCount);
    }
  });

  if (absoluteMinMissing > 0) {
    logs.push(`ℹ️ Fiziksel Sınır Denetimi: Sınıfların toplam kapasite aşımı ${absoluteMinMissing} saattir. Hedeflenebilecek minimum eksiklik: ${absoluteMinMissing} saattir.`);
  }

  function generatePendingList(useMinBlockSize: boolean, currentPlansState: PlanItem[]): PendingAssignment[] {
    const list: PendingAssignment[] = [];
    classes.forEach((sinif) => {
      if (!sinif.aktifPasif) return;
      const sinifPlans = currentPlansState.filter((plan) => isSchedulablePlan(plan) && plan.sinifId === sinif.id);

      Object.entries(sinif.haftalikDersIhtiyaci || {}).forEach(([dersIsmi, iHour]) => {
         const ihtiyacSaat = Number(iHour);
         if (!Number.isFinite(ihtiyacSaat) || ihtiyacSaat <= 0) return;

         const courseObj = courses.find((course) => course.dersAdi === dersIsmi && (!course.kademe || !sinif.kademe || course.kademe === sinif.kademe));
         if (!courseObj) return;

         const assigned = sinifPlans.filter((plan) => plan.dersId === courseObj.id).length;
         const missingHours = ihtiyacSaat - assigned;

         if (missingHours <= 0) return;

         const eligibleTeachers = teachers.filter(
           (teacher) =>
             isActiveEntity(teacher) &&
             canTeacherTeachCourse(teacher, courseObj) &&
             isTeacherCadreCompatible(teacher, sinif, courseObj)
         );

         if (eligibleTeachers.length === 0) return;

         const eligibleRooms = classrooms.filter((room) => isActiveEntity(room) && room.kapasite >= sinif.mevcutOgrenciSayisi && (!room.hizmetBirimi || room.hizmetBirimi === "Tümü" || room.hizmetBirimi === sinif.kademe));
         if (eligibleRooms.length === 0) return;

         let remainingHours = missingHours;
         const courseProfile = getCoursePedagogicalProfile(courseObj);
         const maxBlockHours = useMinBlockSize ? 1 : courseProfile.maxBlockSize;
         while (remainingHours > 0) {
           const blockHours = Math.min(maxBlockHours, remainingHours);
           list.push({ sinif, courseObj, eligibleTeachers, eligibleRooms, hours: blockHours });
           remainingHours -= blockHours;
         }
      });
    });
    return list;
  }

  function solveList(pendingList: PendingAssignment[], maxPhaseRestarts: number): number {
    if (pendingList.length === 0) return 0;

    let currentBestPlans = [...plansCopy];
    let minRemainingMissing = pendingList.reduce((acc, curr) => acc + curr.hours, 0);
    const daysList = finalConfig.activeDays;
    const maxAssignmentBlockHours = Math.max(1, ...pendingList.map((assignment) => assignment.hours));
    const startSlotCache = buildStartSlotCache(daysList, finalConfig, maxAssignmentBlockHours);

    let noImprovementCount = 0;

    for (let attempt = 0; attempt < maxPhaseRestarts; attempt++) {
      let tempPlans = [...plansCopy];
      let tempIndex = buildScheduleIndex(tempPlans, normalizedInput.effectiveAllowedPeriods, normalizedInput.effectiveAvailablePeriods);
      let currentMissing = 0;

      const sortedAssignments = shuffleInPlace([...pendingList], rng).sort((a, b) => {
        const aFlexibility = a.eligibleTeachers.length * a.eligibleRooms.length;
        const bFlexibility = b.eligibleTeachers.length * b.eligibleRooms.length;
        if (aFlexibility !== bFlexibility) return aFlexibility - bFlexibility;
        return b.hours - a.hours;
      });

      let backtrackCount = 0;
      const MAX_BACKTRACKS = attempt === 0 ? 150 : 300; 

      function checkForwardFeasibility(
        currentIndex: typeof tempIndex,
        remainingAssignments: PendingAssignment[]
      ): boolean {
        // 1. Class capacity check (summarized per class)
        const classNeeded = new Map<string, number>();
        for (const ass of remainingAssignments) {
          classNeeded.set(ass.sinif.id, (classNeeded.get(ass.sinif.id) || 0) + ass.hours);
        }

        for (const [classId, neededHours] of classNeeded.entries()) {
          const allowed = normalizedInput.effectiveAllowedPeriods.get(classId) || [];
          let freeCount = 0;
          for (const slot of allowed) {
            if (!currentIndex.classSlot.has(`${classId}|${slot}`)) {
              freeCount++;
            }
          }
          if (freeCount < neededHours) {
            return false;
          }
        }

        // 2. Teacher capacity check
        for (const ass of remainingAssignments) {
          let hasCapacity = false;
          for (const teacher of ass.eligibleTeachers) {
            const currentLoad = currentIndex.teacherWeekly.get(teacher.id) || 0;
            const maxWeekly = teacher.haftalikMaksimumDers ?? Number.POSITIVE_INFINITY;
            if (currentLoad + ass.hours <= maxWeekly) {
              hasCapacity = true;
              break;
            }
          }
          if (!hasCapacity) {
            return false;
          }
        }

        return true;
      }

      function dfs(depth: number): boolean {
        if (depth >= sortedAssignments.length) {
          if (currentMissing < minRemainingMissing) {
            minRemainingMissing = currentMissing;
            currentBestPlans = [...tempPlans];
          }
          if (currentMissing <= absoluteMinMissing) {
            return true;
          }
          return false;
        }

        if (backtrackCount >= MAX_BACKTRACKS) {
          return false;
        }

        const assignment = sortedAssignments[depth];
        const blockHours = assignment.hours;

        const availableStartSlots = [...(startSlotCache.get(blockHours) || [])];
        if (attempt > 0) shuffleInPlace(availableStartSlots, rng);

        const sortedTeachers = shuffleInPlace([...assignment.eligibleTeachers], rng).sort((a, b) => {
          const aLoad = tempIndex.teacherWeekly.get(a.id) || 0;
          const bLoad = tempIndex.teacherWeekly.get(b.id) || 0;
          const aLimit = a.haftalikMaksimumDers || 24;
          const bLimit = b.haftalikMaksimumDers || 24;
          const aUtil = aLoad / aLimit;
          const bUtil = bLoad / bLimit;
          if (Math.abs(aUtil - bUtil) > 0.01) {
            return aUtil - bUtil;
          }
          return aLoad - bLoad;
        });

        const sortedRooms = shuffleInPlace([...assignment.eligibleRooms], rng).sort((a, b) => {
          const aWaste = Math.max(0, a.kapasite - assignment.sinif.mevcutOgrenciSayisi);
          const bWaste = Math.max(0, b.kapasite - assignment.sinif.mevcutOgrenciSayisi);
          return aWaste - bWaste;
        });

        const topCandidates: CandidateDraft[] = [];
        let checkedCombinations = 0;
        let foundCandidatesCount = 0;
        const candidateLimit = optimizationMode === "completeness" ? 3 : 5;
        const maxCombinationsToTry = attempt === 0 ? 700 : 2500;

        for (const startSlot of availableStartSlots) {
          if (foundCandidatesCount >= candidateLimit) break;
          if (checkedCombinations > maxCombinationsToTry) break;

          const [day, spStr] = startSlot.split("-");
          const startPeriodNo = parseInt(spStr, 10);

          const blockSlots = buildBlockSlots(day, startPeriodNo, blockHours, finalConfig);
          if (!blockSlots) continue;

          const allowed = normalizedInput.effectiveAllowedPeriods.get(assignment.sinif.id) || [];
          const allAllowed = blockSlots.every(slot => allowed.includes(slot));
          if (!allAllowed) continue;

          for (const teacher of sortedTeachers) {
            if (foundCandidatesCount >= candidateLimit) break;
            if (checkedCombinations > maxCombinationsToTry) break;

            for (const room of sortedRooms) {
              if (foundCandidatesCount >= candidateLimit) break;
              if (checkedCombinations > maxCombinationsToTry) break;

              checkedCombinations++;

              const stagedPlacements = tryStageBlockOnIndex(
                tempIndex,
                blockSlots,
                teacher,
                assignment.sinif,
                room,
                assignment.courseObj,
                finalConfig
              );

              if (!stagedPlacements) continue;

              foundCandidatesCount++;
              const baseScore = scoreBlockPlacement(
                tempIndex,
                teacher,
                assignment.sinif,
                room,
                day,
                blockSlots[blockSlots.length - 1],
                finalConfig
              );
              const randomizedScore = attempt === 0 ? baseScore : baseScore + rng() * 5;
              keepBestCandidates(topCandidates, {
                score: randomizedScore,
                slots: [...blockSlots],
                teacher,
                room,
              });
              rollbackIndexedPlacements(tempIndex, stagedPlacements);
            }
          }
        }

        topCandidates.sort((a, b) => a.score - b.score);

        let anyChildSucceeded = false;

        for (const candidate of topCandidates) {
          const stagedPlacements = tryStageBlockOnIndex(
            tempIndex,
            candidate.slots,
            candidate.teacher,
            assignment.sinif,
            candidate.room,
            assignment.courseObj,
            finalConfig
          );

          if (!stagedPlacements) continue;

          // Forward Checking / Look-ahead to prune infeasible states early
          const nextAssignments = sortedAssignments.slice(depth + 1);
          if (!checkForwardFeasibility(tempIndex, nextAssignments)) {
            rollbackIndexedPlacements(tempIndex, stagedPlacements);
            continue;
          }

          const selectedPlans = materializeCandidate(candidate, assignment.sinif, assignment.courseObj);
          const prevPlansLength = tempPlans.length;
          tempPlans = [...tempPlans, ...selectedPlans];

          const success = dfs(depth + 1);
          if (success) {
            anyChildSucceeded = true;
            return true;
          }

          rollbackIndexedPlacements(tempIndex, stagedPlacements);
          tempPlans.length = prevPlansLength;

          backtrackCount++;
          if (backtrackCount >= MAX_BACKTRACKS) {
            break;
          }
        }

        if (!anyChildSucceeded && backtrackCount < MAX_BACKTRACKS) {
          backtrackCount++;
          currentMissing += blockHours;
          if (currentMissing < minRemainingMissing) {
            const success = dfs(depth + 1);
            if (success) {
              currentMissing -= blockHours;
              return true;
            }
          }
          currentMissing -= blockHours;
        }

        return false;
      }

      dfs(0);

      if (minRemainingMissing <= absoluteMinMissing) {
        currentBestPlans = tempPlans;
        break;
      }

      if (minRemainingMissing < pendingList.reduce((acc, curr) => acc + curr.hours, 0)) {
        noImprovementCount = 0;
      } else {
        noImprovementCount++;
      }

      if (noImprovementCount >= 4) {
        break;
      }
    }

    const totalTarget = pendingList.reduce((acc, curr) => acc + curr.hours, 0);
    const placedCount = totalTarget - minRemainingMissing;
    plansCopy = currentBestPlans;
    return placedCount;
  }

  if (optimizationMode === "completeness") {
    const listToSolve = generatePendingList(true, plansCopy);
    if (listToSolve.length > 0) {
      logs.push(`🔍 Tamamlama Aşaması: Toplam ${listToSolve.length} adet 1 saatlik bağımsız blok yerleştirilmeye çalışılıyor...`);
      const placedCount = solveList(listToSolve, 30);
      resolvedCount += placedCount;
      const remains = listToSolve.reduce((acc, curr) => acc + curr.hours, 0) - placedCount;
      if (remains === 0) {
        logs.push("🎯 Harika! Tüm 1 saatlik bloklar başarıyla sığdırıldı.");
      } else {
        logs.push(`⚠️ Sonuç: ${placedCount} ders saati yerleştirildi, ${remains} ders saati boş kaldı.`);
      }
    } else {
      logs.push("ℹ️ Eksik haftalık ders ihtiyacı bulunmadı. Yalnızca doğrulama yapıldı.");
    }

  } else if (optimizationMode === "pedagogical") {
    const listToSolve = generatePendingList(false, plansCopy);
    if (listToSolve.length > 0) {
      logs.push(`🔍 Pedagojik Blok Arama: Toplam ${listToSolve.length} adet bütün/blok ders oturumu yerleştirilmeye çalışılıyor...`);
      const placedCount = solveList(listToSolve, 30);
      resolvedCount += placedCount;
      const remains = listToSolve.reduce((acc, curr) => acc + curr.hours, 0) - placedCount;
      if (remains === 0) {
        logs.push("🎯 Harika! Tüm pedagojik blok atamaları başarıyla yerleştirildi.");
      } else {
        logs.push(`⚠️ Sonuç: ${placedCount} ders saati blok olarak yerleştirildi, ${remains} ders saati boş kaldı (pedagojik kısıtlar gevşetilmedi).`);
      }
    } else {
      logs.push("ℹ️ Eksik haftalık ders ihtiyacı bulunmadı. Yalnızca doğrulama yapıldı.");
    }

  } else {
    const p1List = generatePendingList(false, plansCopy);
    if (p1List.length > 0) {
      logs.push(`🔍 [1. Aşama] Pedagojik Blok Uyumlama: Toplam ${p1List.length} adet blok oturum yerleştiriliyor...`);
      const p1PlacedCount = solveList(p1List, 20);
      resolvedCount += p1PlacedCount;
      const p1Remains = p1List.reduce((acc, curr) => acc + curr.hours, 0) - p1PlacedCount;

      if (p1Remains === 0) {
        logs.push("✅ [1. Aşama] Başarılı! Tüm pedagojik bloklar yerleştirildi, 2. aşamaya gerek kalmadı.");
      } else {
        logs.push(`⚠️ [1. Aşama] Kısmi Çözüm: ${p1PlacedCount} ders saati blok halinde yerleştirildi. ${p1Remains} saat yerleşemedi.`);
        
        const p2List = generatePendingList(true, plansCopy);
        if (p2List.length > 0) {
          logs.push(`🔍 [2. Aşama] Serbest Bölme / Tamamlama: Kalan ${p2List.length} saat ders sığdırma amacıyla 1'er saatlik küçük parçalara bölünerek yerleştiriliyor...`);
          const p2PlacedCount = solveList(p2List, 15);
          resolvedCount += p2PlacedCount;
          const p2Remains = p2List.reduce((acc, curr) => acc + curr.hours, 0) - p2PlacedCount;

          if (p2Remains === 0) {
            logs.push("🎯 [2. Aşama] Başarılı! Kalan tüm dersler 1 saatlik bölünmeyle başarıyla sığdırıldı.");
          } else {
            logs.push(`⚠️ [2. Aşama] Tamamlandı: Kalanlardan ${p2PlacedCount} saat daha yerleştirildi. ${p2Remains} saat boş kaldı.`);
          }
        }
      }
    } else {
      logs.push("ℹ️ Eksik haftalık ders ihtiyacı bulunmadı. Yalnızca doğrulama yapıldı.");
    }
  }

  const tempAssignedCounts = new Map<string, number>();
  plansCopy.filter(isSchedulablePlan).forEach((plan) => {
    const key = `${plan.sinifId}-${plan.dersId}`;
    tempAssignedCounts.set(key, (tempAssignedCounts.get(key) || 0) + 1);
  });

  const finalIndex = buildScheduleIndex(plansCopy, normalizedInput.effectiveAllowedPeriods, normalizedInput.effectiveAvailablePeriods);

  classes.forEach((sinif) => {
    Object.entries(sinif.haftalikDersIhtiyaci || {}).forEach(([dersIsmi, iHour]) => {
      const ihtiyacSaat = Number(iHour);
      const courseObj = courses.find((course) => course.dersAdi === dersIsmi && (!course.kademe || !sinif.kademe || course.kademe === sinif.kademe));
      if (!courseObj) return;

      const key = `${sinif.id}-${courseObj.id}`;
      const assigned = tempAssignedCounts.get(key) || 0;
      const missing = ihtiyacSaat - assigned;

      if (missing > 0) {
        unassignedRequirements.push({
          classId: sinif.id,
          className: sinif.sinifAdi,
          courseId: courseObj.id,
          courseName: courseObj.dersAdi,
          missingHours: missing,
          reasons: diagnoseUnassignedRequirement(sinif, courseObj, teachers, classrooms, finalIndex, finalConfig),
          severity: "Kritik",
        });
      }
    });
  });

  if (unassignedRequirements.length > 0) {
    logs.push(`🧭 Eksik ders raporu üretildi. Eksik kalem sayısı: ${unassignedRequirements.length}.`);
  }

  const finalViolations = validateSchedules(plansCopy, teachers, classes, classrooms, courses, finalConfig);
  const remainingHardViolations = finalViolations.filter((violation) => violation.seviye === "Zorunlu");

  if (remainingHardViolations.length === 0) {
    logs.push(`\n📈 Optimizasyon tamamlandı. Toplam ${resolvedCount} işlem yapıldı. Zorunlu kural ihlali kalmadı.`);
  } else {
    logs.push(`\n⚠️ Optimizasyon sonlandı ancak ${remainingHardViolations.length} zorunlu hata kaldı.`);

    const finalBadIds = new Set<string>();
    remainingHardViolations.forEach((violation) => violation.bilesenIds.forEach((id) => finalBadIds.add(id)));
    const removableFinalBadIds = new Set(
      [...finalBadIds].filter((id) => {
        const plan = plansCopy.find((item) => item.id === id);
        return plan ? isAutoGeneratedPlan(plan) : false;
      })
    );
    plansCopy = plansCopy.filter((plan) => !removableFinalBadIds.has(plan.id));

    logs.push(`${removableFinalBadIds.size} kalan otomatik sorunlu kart programdan çıkarıldı.`);
    if (finalBadIds.size > removableFinalBadIds.size) {
      logs.push(`${finalBadIds.size - removableFinalBadIds.size} manuel/mevcut sorunlu kart silinmedi; kullanıcı kontrolü gerekiyor.`);
    }
  }

  const finalIdxForReport = buildScheduleIndex(plansCopy, normalizedInput.effectiveAllowedPeriods, normalizedInput.effectiveAvailablePeriods);
  const classReports: ClassOptimizerReport[] = classes.map((cls) => {
    let weeklyNeed = 0;
    Object.entries(cls.haftalikDersIhtiyaci || {}).forEach(([_, iHour]) => {
      weeklyNeed += Number(iHour);
    });

    const allowed = normalizedInput.effectiveAllowedPeriods.get(cls.id) || [];
    const allowedPeriodsCount = allowed.length;

    const clsCourses = Object.keys(cls.haftalikDersIhtiyaci || {}).map(dersIsmi => {
      return courses.find(course => course.dersAdi === dersIsmi && (!course.kademe || !cls.kademe || course.kademe === cls.kademe));
    }).filter((c): c is Course => !!c);

    const eligibleTeachers = teachers.filter(t => 
      isActiveEntity(t) && clsCourses.some(course => canTeacherTeachCourse(t, course) && isTeacherCadreCompatible(t, cls, course))
    );

    let teacherJointCount = 0;
    allowed.forEach(slot => {
      const anyTeacherAvailable = eligibleTeachers.some(t => {
        const teacherAvail = normalizedInput.effectiveAvailablePeriods.get(t.id) || [];
        return teacherAvail.includes(slot);
      });
      if (anyTeacherAvailable) {
        teacherJointCount++;
      }
    });

    const compatibleRoomsCount = classrooms.filter(r => isActiveEntity(r) && r.kapasite >= cls.mevcutOgrenciSayisi).length;

    const assignedHours = plansCopy.filter(p => isSchedulablePlan(p) && p.sinifId === cls.id).length;
    const missingHours = Math.max(0, weeklyNeed - assignedHours);

    let constraintSource = "NONE";
    const initialAllowedWindow = CLASS_TIME_WINDOWS.find(w => w.sinifId === cls.id);
    const initialAllowed = initialAllowedWindow ? initialAllowedWindow.izinliPeriyotlar : [];

    if (cls.uygunPeriyotlar && cls.uygunPeriyotlar.length > 0) {
      const sortedA = [...cls.uygunPeriyotlar].sort();
      const sortedB = [...initialAllowed].sort();
      const match = sortedA.length === sortedB.length && sortedA.every((val, i) => val === sortedB[i]);
      if (match) {
        constraintSource = "CLASS_TIME_WINDOWS";
      } else {
        constraintSource = "USER";
      }
    } else {
      const policy = getLevelPolicy(cls);
      if (policy && policy.hardWindows && policy.hardWindows.length > 0) {
        constraintSource = "PRESET";
      } else {
        constraintSource = "NONE";
      }
    }

    return {
      classId: cls.id,
      className: cls.sinifAdi,
      weeklyNeed,
      allowedPeriodsCount,
      teacherJointAvailability: teacherJointCount,
      classroomAvailability: compatibleRoomsCount,
      assignedHours,
      missingHours,
      constraintSource,
    };
  });

  return {
    plans: plansCopy,
    logs,
    resolvedCount,
    unassignedRequirements,
    classReports,
  };
}

self.onmessage = (event: MessageEvent<WorkerInputMessage>) => {
  const { currentPlans, teachers, classes, classrooms, courses, config, options } = event.data;
  try {
    const result = runAlgorithmicOptimizerSync(
      currentPlans,
      teachers,
      classes,
      classrooms,
      courses,
      config,
      options
    );
    self.postMessage({ success: true, result });
  } catch (error: unknown) {
    const errMessage = error instanceof Error ? error.message : String(error);
    self.postMessage({ success: false, error: errMessage });
  }
};
