/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Ata Akademi ders programı kural motoru - Modüler Revizyon.
 */

import { PlanItem, Teacher, ClassUnit, Classroom, Course, PlanTuru } from "../types";
import { SchoolScheduleConfig, getMasterTimeSlots, getActivePeriodsCountForDay } from "./timeSettings";

// Re-export level policy types and functions
export type { 
  AtaSeviye, 
  ViolationLevel, 
  PeriodRule, 
  ScheduleWindowPolicy, 
  LevelSchedulePolicy, 
} from "./levelPolicy";

export { 
  LEVEL_POLICIES, 
  getLevelPolicy, 
  isSlotAllowedForClassPolicy, 
  normalizeSeviye,
  getLevelWindowViolation
} from "./levelPolicy";

// Re-export pedagogical profiles
export type { 
  CoursePedagogicalProfile, 
} from "./pedagogicalProfiles";

export { 
  BRANCH_PEDAGOGICAL_PROFILES, 
  getCoursePedagogicalProfile 
} from "./pedagogicalProfiles";

// Re-export schedule index and fast-check functions
export type { 
  ScheduleIndex, 
  IndexedPlacement, 
} from "./scheduleIndex";

export { 
  buildScheduleIndex, 
  canPlaceAtaPlanFast, 
  tryStageBlockOnIndex,
  isSchedulablePlan,
  canTeacherTeachCourse,
  isTeacherCadreCompatible,
  isTeacherAvailable,
  getDefaultWeeklyBounds,
  rollbackIndexedPlacements,
  getDay,
  getPeriodNo
} from "./scheduleIndex";

// Re-export constraint validation
export { validateSchedules } from "./constraintEngine";

import { 
  getLevelPolicy, 
  isSlotAllowedForClassPolicy, 
  getLevelWindowViolation, 
  windowMatches 
} from "./levelPolicy";

import { 
  ScheduleIndex, 
  getDay, 
  getPeriodNo, 
  canTeacherTeachCourse, 
  isTeacherCadreCompatible, 
  isTeacherAvailable, 
  getDefaultWeeklyBounds, 
  calculateGap, 
  shiftPeriod 
} from "./scheduleIndex";

const AUTO_PLAN_ID_PREFIX = "app-auto-";

export interface UnassignedRequirement {
  classId: string;
  className: string;
  courseId: string;
  courseName: string;
  missingHours: number;
  reasons: string[];
  severity: "Kritik" | "Uyarı";
}

export interface ClassOptimizerReport {
  classId: string;
  className: string;
  weeklyNeed: number;
  allowedPeriodsCount: number;
  teacherJointAvailability: number;
  classroomAvailability: number;
  assignedHours: number;
  missingHours: number;
  constraintSource: string;
}

export interface EffectiveSchedulingInput {
  plans: PlanItem[];
  teachers: Teacher[];
  classes: ClassUnit[];
  classrooms: Classroom[];
  courses: Course[];
  config: SchoolScheduleConfig;
  effectiveAllowedPeriods: Map<string, string[]>;
  effectiveAvailablePeriods: Map<string, string[]>;
}

export interface AtaOptimizerResult {
  plans: PlanItem[];
  logs: string[];
  resolvedCount: number;
  unassignedRequirements: UnassignedRequirement[];
  classReports?: ClassOptimizerReport[];
}

const DEFAULT_ATA_AKADEMI_CONFIG: SchoolScheduleConfig = {
  activeDays: ["Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi", "Pazar"],
  longDays: ["Salı", "Perşembe", "Cuma"],
  longDaysHours: { start: "08:30", end: "20:00" },
  regularDaysHours: { start: "08:30", end: "17:00" },
  lessonDuration: 40,
  recessDuration: 10,
};

export function getFinalConfig(config?: SchoolScheduleConfig): SchoolScheduleConfig {
  return config || DEFAULT_ATA_AKADEMI_CONFIG;
}

function indexKey(...parts: Array<string | number>): string {
  return parts.join("|");
}

function getTeacher(teacherId: string, teachers: Teacher[]): Teacher | undefined {
  return teachers.find((teacher) => teacher.id === teacherId);
}

function getClass(classId: string, classes: ClassUnit[]): ClassUnit | undefined {
  return classes.find((cls) => cls.id === classId);
}

function getRoom(roomId: string, classrooms: Classroom[]): Classroom | undefined {
  return classrooms.find((room) => room.id === roomId);
}

function getCourse(courseId: string, courses: Course[]): Course | undefined {
  return courses.find((course) => course.id === courseId);
}

function getPlanIds(plans: PlanItem[]): string[] {
  return plans.map((plan) => plan.id);
}

export function isAutoGeneratedPlan(plan: PlanItem): boolean {
  return plan.id.startsWith(AUTO_PLAN_ID_PREFIX);
}

export function isActiveEntity(entity: { aktifPasif?: boolean }): boolean {
  return entity.aktifPasif !== false;
}

export function buildBlockSlots(
  day: string,
  startPeriodNo: number,
  blockHours: number,
  config: SchoolScheduleConfig
): string[] | undefined {
  const activeCount = getActivePeriodsCountForDay(day, config);
  const slots: string[] = [];
  let periodNo = startPeriodNo;

  while (slots.length < blockHours) {
    if (periodNo > activeCount) return undefined;
    if (config.ogleArasiPeriyotNo !== undefined && periodNo === config.ogleArasiPeriyotNo) {
      periodNo++;
      continue;
    }
    slots.push(`${day}-${periodNo}`);
    periodNo++;
  }

  return slots;
}

function makeAutoPlan(
  sinif: ClassUnit,
  course: Course,
  teacher: Teacher,
  room: Classroom,
  slot: string
): PlanItem {
  return {
    id: `${AUTO_PLAN_ID_PREFIX}${Date.now()}-${Math.random().toString(36).substring(2, 8)}`,
    planTuru: course.brans === "Rehberlik" ? PlanTuru.REHBERLIK : PlanTuru.NORMAL_DERS,
    durum: "Taslak",
    sinifId: sinif.id,
    dersId: course.id,
    ogretmenId: teacher.id,
    derslikId: room.id,
    periyotId: slot,
  };
}

export function normalizeSchedulingInput(
  plans: PlanItem[],
  teachers: Teacher[],
  classes: ClassUnit[],
  classrooms: Classroom[],
  courses: Course[],
  config?: SchoolScheduleConfig
): EffectiveSchedulingInput {
  const finalConfig: SchoolScheduleConfig = config || {
    activeDays: ["Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi", "Pazar"],
    longDays: ["Salı", "Perşembe", "Cuma"],
    longDaysHours: { start: "08:30", end: "20:00" },
    regularDaysHours: { start: "08:30", end: "17:00" },
    lessonDuration: 40,
    recessDuration: 10,
    ogleArasiPeriyotNo: 5
  };
  const effectiveAllowedPeriods = new Map<string, string[]>();
  const effectiveAvailablePeriods = new Map<string, string[]>();

  const activePeriodsList: string[] = [];
  const activeCount = Math.max(14, getMasterTimeSlots(finalConfig).length);
  finalConfig.activeDays.forEach(day => {
    for (let pNo = 1; pNo <= activeCount; pNo++) {
      if (finalConfig.ogleArasiPeriyotNo && pNo === finalConfig.ogleArasiPeriyotNo) continue;
      activePeriodsList.push(`${day}-${pNo}`);
    }
  });

  classes.forEach(cls => {
    let allowed: string[] = [];
    if (cls.uygunPeriyotlar && cls.uygunPeriyotlar.length > 0) {
      allowed = [...cls.uygunPeriyotlar];
    } else {
      const policy = getLevelPolicy(cls);
      if (policy && policy.hardWindows && policy.hardWindows.length > 0) {
        allowed = activePeriodsList.filter(slot => {
          const day = getDay(slot);
          const pNo = getPeriodNo(slot);
          return policy.hardWindows!.some(window => windowMatches(window, day, pNo, activeCount));
        });
      } else {
        allowed = [...activePeriodsList];
      }
    }
    effectiveAllowedPeriods.set(cls.id, allowed);
  });

  teachers.forEach(teacher => {
    let available: string[] = [];
    if (teacher.uygunPeriyotlar && teacher.uygunPeriyotlar.length > 0) {
      available = [...teacher.uygunPeriyotlar];
    } else {
      available = activePeriodsList.filter(slot => {
        const day = getDay(slot);
        const pNo = getPeriodNo(slot);
        const hasDay = !teacher.uygunGunler || teacher.uygunGunler.length === 0 || teacher.uygunGunler.includes(day);
        const hasHour = !teacher.uygunSaatler || teacher.uygunSaatler.length === 0 || teacher.uygunSaatler.includes(String(pNo));
        return hasDay && hasHour;
      });
    }
    effectiveAvailablePeriods.set(teacher.id, available);
  });

  return {
    plans,
    teachers,
    classes,
    classrooms,
    courses,
    config: finalConfig,
    effectiveAllowedPeriods,
    effectiveAvailablePeriods
  };
}

export function countAllowedSlotsForClass(
  cls: ClassUnit,
  finalConfig: SchoolScheduleConfig,
  effectiveAllowedPeriods?: Map<string, string[]>
): number {
  if (cls.uygunPeriyotlar && cls.uygunPeriyotlar.length > 0) {
    return cls.uygunPeriyotlar.length;
  }

  let allowed = 0;
  finalConfig.activeDays.forEach((day) => {
    const activeCount = getActivePeriodsCountForDay(day, finalConfig);

    for (let periodNo = 1; periodNo <= activeCount; periodNo++) {
      if (finalConfig.ogleArasiPeriyotNo !== undefined && periodNo === finalConfig.ogleArasiPeriyotNo) continue;

      if (!isSlotAllowedForClassPolicy(cls, day, periodNo, activeCount)) continue;

      allowed++;
    }
  });

  return allowed;
}

function calculateProjectedTeacherGapsFromIndex(
  index: ScheduleIndex,
  teacherId: string,
  day: string,
  config: SchoolScheduleConfig
): number {
  const periods = [...(index.teacherDayPeriods.get(indexKey(teacherId, day)) || new Set<number>())]
    .filter(Number.isFinite)
    .sort((a, b) => a - b);

  let totalGaps = 0;
  for (let i = 1; i < periods.length; i++) {
    totalGaps += calculateGap(periods[i - 1], periods[i], config);
  }

  return totalGaps;
}

export interface CandidateDraft {
  score: number;
  slots: string[];
  teacher: Teacher;
  room: Classroom;
}

export function scoreBlockPlacement(
  index: ScheduleIndex,
  teacher: Teacher,
  cls: ClassUnit,
  room: Classroom,
  day: string,
  lastSlot: string,
  finalConfig: SchoolScheduleConfig
): number {
  const teacherWeeklyLoad = index.teacherWeekly.get(teacher.id) || 0;
  const teacherDailyLoad = index.teacherDaily.get(indexKey(teacher.id, day)) || 0;
  const idealDaily = teacher.idealGunlukDers || 6;
  const weeklyLimit = teacher.haftalikMaksimumDers || Math.max(teacherWeeklyLoad, 1);
  const capacityWaste = Math.max(0, room.kapasite - cls.mevcutOgrenciSayisi);
  const gaps = calculateProjectedTeacherGapsFromIndex(index, teacher.id, day, finalConfig);

  let score = 0;
  // Kademeli (quadratic) yük cezası: Yükü fazla olan öğretmenlere ders verilmesini daha agresif şekilde engeller
  score += Math.pow(teacherWeeklyLoad / weeklyLimit, 2) * 45;
  score += Math.max(0, teacherDailyLoad - idealDaily) * 10;
  score += gaps * 4;
  score += capacityWaste / 10;

  const activeCount = getActivePeriodsCountForDay(day, finalConfig);
  const levelViolation = getLevelWindowViolation(cls, day, getPeriodNo(lastSlot), activeCount);
  if (levelViolation?.seviye === "Esnek") score += 25;

  return score;
}

export function materializeCandidate(
  draft: CandidateDraft,
  sinif: ClassUnit,
  course: Course
): PlanItem[] {
  return draft.slots.map((slot) => makeAutoPlan(sinif, course, draft.teacher, draft.room, slot));
}

export function buildStartSlotCache(
  daysList: string[],
  finalConfig: SchoolScheduleConfig,
  maxBlockHours: number
): Map<number, string[]> {
  const cache = new Map<number, string[]>();

  for (let blockHours = 1; blockHours <= maxBlockHours; blockHours++) {
    const slots: string[] = [];

    daysList.forEach((day) => {
      const activeCount = getActivePeriodsCountForDay(day, finalConfig);

      for (let startPeriodNo = 1; startPeriodNo <= activeCount; startPeriodNo++) {
        if (finalConfig.ogleArasiPeriyotNo !== undefined && startPeriodNo === finalConfig.ogleArasiPeriyotNo) continue;

        const blockSlots = buildBlockSlots(day, startPeriodNo, blockHours, finalConfig);
        if (blockSlots) slots.push(`${day}-${startPeriodNo}`);
      }
    });

    cache.set(blockHours, slots);
  }

  return cache;
}

export function createMulberry32(seed: number): () => number {
  let s = seed;
  return function() {
    let t = s += 0x6D2B79F5;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function shuffleInPlace<T>(items: T[], rng?: () => number): T[] {
  const randomFunc = rng || Math.random;
  for (let i = items.length - 1; i > 0; i--) {
    const j = Math.floor(randomFunc() * (i + 1));
    [items[i], items[j]] = [items[j], items[i]];
  }
  return items;
}

export function keepBestCandidates<T extends { score: number }>(candidates: T[], candidate: T, maxSize = 8): void {
  candidates.push(candidate);
  candidates.sort((a, b) => a.score - b.score);
  if (candidates.length > maxSize) candidates.length = maxSize;
}

function pickCandidate<T>(candidates: T[], attempt: number): T | undefined {
  if (candidates.length === 0) return undefined;
  if (attempt === 0) return candidates[0];

  const topWindow = Math.min(candidates.length, 3);
  return candidates[Math.floor(Math.random() * topWindow)];
}

export function diagnoseUnassignedRequirement(
  sinif: ClassUnit,
  course: Course,
  teachers: Teacher[],
  classrooms: Classroom[],
  index: ScheduleIndex,
  finalConfig: SchoolScheduleConfig
): string[] {
  const reasons: string[] = [];

  const compatibleTeachers = teachers.filter(
    (teacher) =>
      isActiveEntity(teacher) &&
      canTeacherTeachCourse(teacher, course) &&
      isTeacherCadreCompatible(teacher, sinif, course)
  );

  if (compatibleTeachers.length === 0) {
    reasons.push("Öğretmen Kilidi: Dersi verebilecek aktif ve kademe uyumlu öğretmen tanımlanmamış.");
  } else if (compatibleTeachers.every((teacher) => (index.teacherWeekly.get(teacher.id) || 0) >= (teacher.haftalikMaksimumDers ?? Number.POSITIVE_INFINITY))) {
    reasons.push("Öğretmen Kilidi: Uygun öğretmenlerin tamamının haftalık maksimum ders yükü limiti dolu.");
  }

  const compatibleRooms = classrooms.filter(
    (room) =>
      isActiveEntity(room) &&
      room.kapasite >= sinif.mevcutOgrenciSayisi &&
      (!room.hizmetBirimi || room.hizmetBirimi === "Tümü" || room.hizmetBirimi === sinif.kademe)
  );
  if (compatibleRooms.length === 0) {
    reasons.push("Derslik Kilidi: Sınıf mevcuduna uygun kapasitede aktif derslik bulunamadı.");
  }

  // Get class allowed slots using override logic
  let allowedSlots: string[] = [];
  if (sinif.uygunPeriyotlar && sinif.uygunPeriyotlar.length > 0) {
    allowedSlots = [...sinif.uygunPeriyotlar];
  } else {
    finalConfig.activeDays.forEach((day) => {
      const activeCount = getActivePeriodsCountForDay(day, finalConfig);
      for (let periodNo = 1; periodNo <= activeCount; periodNo++) {
        if (finalConfig.ogleArasiPeriyotNo !== undefined && periodNo === finalConfig.ogleArasiPeriyotNo) continue;
        if (!isSlotAllowedForClassPolicy(sinif, day, periodNo, activeCount)) continue;
        allowedSlots.push(`${day}-${periodNo}`);
      }
    });
  }

  const occupiedCount = allowedSlots.filter(slot => index.classSlot.has(indexKey(sinif.id, slot))).length;
  const freeSlots = allowedSlots.filter(slot => !index.classSlot.has(indexKey(sinif.id, slot)));
  const freeCount = freeSlots.length;

  if (allowedSlots.length === 0) {
    reasons.push("Fiziksel Pencere Açığı: Sınıfın seviye/pencere kısıtlarına göre tanımlı izinli periyodu yok.");
  } else if (freeCount === 0) {
    reasons.push("Fiziksel Pencere Açığı: Sınıfın izinli zaman penceresindeki tüm periyotlar dolu.");
  }

  if (reasons.length === 0) {
    let teacherBusyInAllFreeSlots = true;
    let roomBusyInAllFreeSlots = true;

    for (const slot of freeSlots) {
      const anyTeacherFree = compatibleTeachers.some(t => {
        const isWeeklyFull = (index.teacherWeekly.get(t.id) || 0) >= (t.haftalikMaksimumDers ?? Number.POSITIVE_INFINITY);
        const isSlotBusy = index.teacherSlot.has(indexKey(t.id, slot));
        
        let teacherAllows = true;
        if (index.effectiveAvailablePeriods && index.effectiveAvailablePeriods.has(t.id)) {
          teacherAllows = index.effectiveAvailablePeriods.get(t.id)!.includes(slot);
        } else {
          const day = getDay(slot);
          const pNo = getPeriodNo(slot);
          teacherAllows = isTeacherAvailable(t, day, pNo, slot);
        }
        
        return !isWeeklyFull && !isSlotBusy && teacherAllows;
      });

      if (anyTeacherFree) {
        teacherBusyInAllFreeSlots = false;
      }

      const anyRoomFree = compatibleRooms.some(r => !index.roomSlot.has(indexKey(r.id, slot)));
      if (anyRoomFree) {
        roomBusyInAllFreeSlots = false;
      }
    }

    if (teacherBusyInAllFreeSlots) {
      reasons.push("Öğretmen Kilidi: Kalan sınıf boş periyotlarında dersi verebilecek öğretmenlerin programı dolu veya uygun değil.");
    }
    if (roomBusyInAllFreeSlots) {
      reasons.push("Derslik Kilidi: Kalan sınıf boş periyotlarında uygun kapasitedeki tüm derslikler dolu.");
    }
  }

  if (reasons.length === 0) {
    reasons.push("Kombinasyon Kilidi: Sınıfta boş yer, öğretmende boş yer ve uygun derslik arasında ortak bir kesişim kümesi yok (Spatiotemporal kilit).");
  }

  return reasons;
}
